/********************************************************************
* ExampleEventDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ExampleEventDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableExampleEventDictionary();
extern void G__cpp_setup_inheritanceExampleEventDictionary();
extern void G__cpp_setup_typetableExampleEventDictionary();
extern void G__cpp_setup_memvarExampleEventDictionary();
extern void G__cpp_setup_globalExampleEventDictionary();
extern void G__cpp_setup_memfuncExampleEventDictionary();
extern void G__cpp_setup_funcExampleEventDictionary();
extern void G__set_cpp_environmentExampleEventDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ExampleEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ExampleEventDictionaryLN_TClass;
extern G__linked_taginfo G__ExampleEventDictionaryLN_TBuffer;
extern G__linked_taginfo G__ExampleEventDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__ExampleEventDictionaryLN_TObject;
extern G__linked_taginfo G__ExampleEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ExampleEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExampleEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ExampleEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExampleEventDictionaryLN_ExampleParticle;
extern G__linked_taginfo G__ExampleEventDictionaryLN_ExampleEvent;
extern G__linked_taginfo G__ExampleEventDictionaryLN_vectorlEExampleParticlecOallocatorlEExampleParticlegRsPgR;
extern G__linked_taginfo G__ExampleEventDictionaryLN_vectorlEExampleParticlecOallocatorlEExampleParticlegRsPgRcLcLiterator;
extern G__linked_taginfo G__ExampleEventDictionaryLN_reverse_iteratorlEvectorlEExampleParticlecOallocatorlEExampleParticlegRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
