/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYPDFV3
#define MYPDFV3

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyPdfV3 : public RooAbsPdf {
public:
  MyPdfV3() {} ; 
  MyPdfV3(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _A,
	      RooAbsReal& _B);
  MyPdfV3(const MyPdfV3& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyPdfV3(*this,newname); }
  inline virtual ~MyPdfV3() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MyPdfV3,1) // Your description goes here...
};
 
#endif
