/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYPDFV2
#define MYPDFV2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyPdfV2 : public RooAbsPdf {
public:
  MyPdfV2() {} ; 
  MyPdfV2(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _A,
	      RooAbsReal& _B);
  MyPdfV2(const MyPdfV2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyPdfV2(*this,newname); }
  inline virtual ~MyPdfV2() { }

protected:

  RooRealProxy x ;
  RooRealProxy A ;
  RooRealProxy B ;
  
  Double_t evaluate() const ;

private:

  ClassDef(MyPdfV2,1) // Your description goes here...
};
 
#endif
