/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooCFAuto000Pdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCFAuto000Pdf) 

 RooCFAuto000Pdf::RooCFAuto000Pdf(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _a) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   a("a","a",this,_a)
 { 
 } 


 RooCFAuto000Pdf::RooCFAuto000Pdf(const RooCFAuto000Pdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   a("a",this,other.a)
 { 
 } 



 Double_t RooCFAuto000Pdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return x*x+a ; 
 } 



