/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooGenPdfPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooGenPdfPdf) 

 RooGenPdfPdf::RooGenPdfPdf(const char *name, const char *title, 
                        RooAbsReal& _y,
                        RooAbsReal& _alpha) :
   RooAbsPdf(name,title), 
   y("y","y",this,_y),
   alpha("alpha","alpha",this,_alpha)
 { 
 } 


 RooGenPdfPdf::RooGenPdfPdf(const RooGenPdfPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   y("y",this,other.y),
   alpha("alpha",this,other.alpha)
 { 
 } 



 Double_t RooGenPdfPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return (1+0.1*fabs(y)+sin(sqrt(fabs(y*alpha+0.1)))) ; 
 } 



